#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  if [[ "$OSTYPE" == darwin* ]]; then
    export LANG='en_US.UTF-8'
  else
    export LANG='es_ES.UTF-8'
  fi
fi

if [[ -z "$LC_ALL" ]]; then
  if [[ "$OSTYPE" == darwin* ]]; then
    export LC_ALL='en_US.UTF-8'
  else
    export LC_ALL='es_ES.UTF-8'
  fi
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/bin
  $HOME/.composer/vendor/bin
  $HOME/.npm-packages/bin
  $HOME/.config/composer/vendor/bin
  /usr/local/{bin,sbin}
  $path
)

fpath=(
  $HOME/.zfunctions
  $fpath
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
